openapi: 3.0.0
info:
  title: Recytech API
  version: 1.0.0
  description: Documentation des routes de l'API Recytech

servers:
  - url: http://localhost:3000/api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        email:
          type: string
          example: "exemple@mail.com"
        name:
          type: string
          example: "Jean Dupont"

security:
  - bearerAuth: []

paths:
  /auth/register:
    post:
      summary: "Créer un nouvel utilisateur"
      tags:
        - Authentification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        '201':
          description: Utilisateur créé avec succès
        '400':
          description: Utilisateur déjà existant

  /auth/login:
    post:
      summary: "Connexion utilisateur"
      tags:
        - Authentification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Connexion réussie
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Identifiants invalides

  /user/me:
    get:
      summary: "Récupérer le profil utilisateur"
      tags:
        - Utilisateur
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Informations utilisateur
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Non autorisé

    put:
      summary: "Mettre à jour le profil utilisateur"
      tags:
        - Utilisateur
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: Profil mis à jour
        '401':
          description: Non autorisé
